from __future__ import annotations

import copy
import logging
import uuid
from dataclasses import dataclass, field
from typing import Optional

import numpy as np
import torch

from modelsmc.tasks import BaseTask

logger = logging.getLogger("ModelSMC")


@dataclass
class Particle:
    """A candidate simulator in the SMC population.

    A particle is the fundamental unit of the discovery process.  It holds the
    simulator source code (``implementation``) together with all metadata that
    accumulates as the particle is evaluated: fitness score, LLM feedback,
    performance metrics, and a chain of ancestor particles that records how the
    code evolved over iterations.

    Particles start out with only ``implementation`` set; all other fields are
    ``None`` / empty and are populated by the weighting step
    (``SMCEngine.weight_particle``).

    Attributes:
        implementation:  Source code of the simulator as a string.  May be
                         Python or R; detected at runtime via
                         ``detect_code_type``.
        uuid:            Unique identifier, auto-generated at creation.
        ancestors:       Ancestry chain (oldest first) of
                         ``Ancestor`` snapshots.  Used as few-shot context
                         for the LLM during propagation.  Empty for
                         the initial base-simulator particle.
        metrics:         Evaluation metrics dict populated after weighting
                         (e.g. ``{"eval_metrics": {"mse": 3.2}}``).
                         Empty dict until evaluated.
        times:           Wall-clock durations for each evaluation sub-step:
                         ``dt_optimization_sec``, ``dt_evaluation_sec``,
                         ``dt_feedback_sec``.  ``None`` until evaluated.
        results_folder:  Basename of the per-particle output directory
                         (e.g. ``"iter-2_p7"``).  ``None`` until evaluated.
        particle_index:  Global integer index, used for output directory
                         naming and CSV logging.  ``None`` until evaluated.
        log_weight:      Scalar log fitness score assigned during weighting.
                         Higher values indicate better fit.  ``None`` until
                         evaluated; ``-inf`` for failed evaluations.
        feedback:        Natural-language diagnostic string produced by the
                         LLM feedback module after evaluation.  Guides the
                         next propagation step.  ``None`` until evaluated.
        scm_definition:  Optional Structural Causal Model (SCM) graph
                         definition generated by the LLM alongside the
                         simulator code.  ``None`` if the LLM did not produce
                         one.
        evaluated:       ``True`` once ``weight_particle`` has successfully
                         written all evaluation fields (``log_weight``,
                         ``feedback``, ``metrics``, ``times``,
                         ``results_folder``, ``particle_index``).  Used as a
                         single, unambiguous gate for the "already evaluated"
                         skip-check in ``SMCEngine.weight``.
        _llm_history_propagation:
                         Raw DSPy LM call history captured during the
                         propagation step, attached only when
                         ``config.save_llm_history`` is enabled so that it can
                         be persisted to disk during weighting (see
                         ``SMCEngine._save_llm_history``).  ``None`` for copied
                         particles and whenever history saving is disabled.
    """

    implementation: str
    uuid: str = field(default_factory=lambda: str(uuid.uuid4()))
    ancestors: list[Ancestor] = field(default_factory=list)

    metrics: Optional[dict] = field(default_factory=dict)
    times: Optional[dict] = None
    results_folder: Optional[str] = None
    particle_index: Optional[int] = None
    log_weight: Optional[float] = None
    feedback: Optional[str] = None
    scm_definition: Optional[str] = None
    evaluated: bool = False
    _llm_history_propagation: Optional[list] = None


@dataclass(frozen=True)
class Ancestor:
    """Immutable snapshot of a particle's state at evaluation time.

    When the propagation step mutates a particle (``SMCEngine.sample_proposal``),
    it first captures the current particle's state as an ``Ancestor`` and
    prepends it to the new particle's ``ancestors`` list.  The ancestry chain
    (ordered most-recent first) is passed to the LLM as few-shot context,
    letting it see the trajectory of code versions and their feedback.

    ``frozen=True`` ensures that historical records cannot be accidentally
    modified once created.

    Attributes:
        implementation:  Simulator source code at the time of capture.
        feedback:        LLM diagnostic feedback received after evaluation.
        scm_definition:  SCM definition at the time of capture (may be
                         ``None`` if the LLM did not produce one).
        uuid:            UUID of the originating particle.
        log_weight:      Log fitness score assigned to the particle at
                         evaluation time.
    """

    implementation: str
    feedback: str
    scm_definition: str
    uuid: str
    log_weight: float


class ParticlePool:
    """Efficient container for a fixed-size population of particles.

    ``ParticlePool`` is the data structure passed between the three main SMC
    steps (resample, propagate, weight).  After multinomial resampling, the
    pool will generally contain duplicate references to high-fitness particles;
    the pool stores each unique particle only once and uses an index vector to
    represent the full population, avoiding unnecessary object copies.

    Internal layout:

    - ``__unique_particles``: list of distinct ``Particle`` objects, keyed by
      UUID.
    - ``__pool``: 1-D integer tensor of length N whose entries are indices
      into ``__unique_particles``.  A value appearing k times means the
      corresponding particle is present k times in the population.

    All public methods return deep copies of stored particles so that callers
    can freely mutate the returned objects without affecting the pool's
    internal state.
    """

    __unique_particles: list[Particle]
    __pool: torch.Tensor

    def __init__(self, particles: list[Particle]) -> None:
        """Initialise the pool from a (possibly duplicated) list of particles.

        Unique particles (identified by UUID) are stored once in
        ``__unique_particles``; ``__pool`` records which slot each position in
        the population refers to.

        Args:
            particles: List of particles defining the initial population.
                       May contain duplicates (e.g. after resampling).
        """
        uuid_to_index: dict[str, int] = {}
        unique_particles: list[Particle] = []
        pool_indices: list[int] = []

        for particle in particles:
            if particle.uuid not in uuid_to_index:
                uuid_to_index[particle.uuid] = len(unique_particles)
                unique_particles.append(copy.deepcopy(particle))
            pool_indices.append(uuid_to_index[particle.uuid])

        self.__unique_particles = unique_particles
        self.__pool = torch.tensor(pool_indices, dtype=torch.long)

    def get_log_weights(self) -> np.ndarray:
        """Return log-weights for all N population slots, including duplicates.

        The returned array has length ``len(self)``.  Each entry is a deep
        copy of the weight stored in ``__unique_particles``, so callers cannot
        mutate internal state through this array.

        Returns:
            Array of shape (N,) containing the log-weight of each population
            slot.

        Raises:
            ValueError: If any particle in the pool has ``log_weight=None``
                        (i.e. it has not been evaluated yet).
        """
        weights = []
        for i in self.__pool.tolist():
            lw = copy.deepcopy(self.__unique_particles[i].log_weight)
            if lw is None:
                raise ValueError(
                    f"Particle at pool index {i} has log_weight=None. "
                    "All particles must be evaluated before calling get_log_weights()."
                )
            weights.append(lw)
        return np.array(weights)

    def get_particles(self) -> list[Particle]:
        """Return all N population slots as a list, including duplicates.

        The list has length ``len(self)``.  Each entry is a deep copy of the
        corresponding unique particle, so callers can safely mutate the
        returned objects (e.g. to fill in evaluation results) without
        affecting the pool's internal state.

        Returns:
            List of ``Particle`` objects representing the full population
            (may contain multiple copies of the same particle).
        """
        return [copy.deepcopy(self.__unique_particles[i]) for i in self.__pool.tolist()]

    def __len__(self) -> int:
        """Return the population size N, counting duplicates."""
        return len(self.__pool)


@dataclass
class DiscoveryContext:
    """Bundles all inputs needed for one SMC step.

    A single ``DiscoveryContext`` instance is created per experiment run and
    shared (via ``deepcopy``) across all Ray workers.  The only field that
    varies between workers is ``save_dir``, which is set to a particle-specific
    path just before each parallel weighting call.

    Attributes:
        task:       Task object providing the evaluation function, data
                    loader, base simulator, and task description.
        train_data: Training observations tensor used for parameter optimisation
                    (SBI).  Shape is task-specific (e.g., [n_samples, n_features]
                    or [n_samples, time_steps]).
        valid_data: Held-out validation observations tensor used to compute the
                    fitness metric and evaluation plots.  Same shape format as
                    ``train_data``.
        save_dir:   Output directory for this particle's results (code,
                    parameter estimates, plots).  ``None`` at construction;
                    set per-particle in ``SMCEngine.weight`` before each
                    parallel evaluation call.

    Properties (delegated to ``task``):
        task_description:      Natural-language description of the modelling
                               task, passed to the LLM as context.
        signature_description: Description of the simulator's input/output
                               signature, passed to the LLM.
        base_simulator:        Source code of the hand-coded base simulator
                               provided with the task.
    """

    def __init__(
        self,
        task: BaseTask,
        train_data: torch.Tensor,
        valid_data: torch.Tensor,
        save_dir: str | None = None,
    ):
        self.task = task
        self.train_data = train_data
        self.valid_data = valid_data
        self.save_dir = save_dir

    task_description = property(lambda self: self.task.get_task_description())
    signature_description = property(lambda self: self.task.get_signature_description())
    base_simulator = property(lambda self: self.task.base_simulator)
